# Generated by Django 5.2.7 on 2025-10-29 13:35

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditem',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], default=datetime.datetime(2025, 10, 29, 13, 35, 45, 473556, tzinfo=datetime.timezone.utc), max_length=10),
            preserve_default=False,
        ),
    ]
